### ISSUE TITLE
Допомога з розгортанням

### ISSUE THREAD

**Issue by SergiiVdovareize** [SergiiVdovareize/Support-Ukraine#3]
Якщо Ви волонтер, сбираєте гроші на потреби Збройних Сил України, Територіальної Оборони або для допомоги цивільному населенню, та Вам потрібна безкоштовна технічна допомога с розгортанням сторінки донатів, то залиште свій запит у коментарях.
Вкажіть свій контакт для зв'язку.

**Comment by DariRihtgofen** [comment]
Привіт! Потребна допомога з розгортанням сторінки для донатів. Telegram: @DariRihtgofen
